# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26642c1952104b713f82b5c881ce8a423c9c0e0eacdce7f8868a8def1a01efc64afd06a3492dc078752daa18988ed87b2f526246733dd2126b1bf3463c66bae

test:
  secret_key_base: 8aaa87d8f9004730da79e0cd13cc87ca80973a13ec8ce810a257493d2a50071ee4e60238a79780222069aaf86524f2c95c8b944582f4e77c9dd4e7d313b33a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
